# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ytp'blog
subtitle: 杨庭培的博客
description: 记录分享美好生活、学习笔记、工作经验、编程开发技巧等，总之在这里你会发现了一个兴趣广泛且爱折腾的程序员。
keywords:
  - 计算机
  - 互联网
  - 程序员
  - 编程开发
  - 学习笔记
  - 前端开发
author: ytp
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 1 #过滤器优先权
  enable_page: all # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法
#hexo-butterfly-footer-marcus
#see https://blog.marcus233.top/p/footer.html
footer_beautify:
  enable: true
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  layout: # 挂载容器类型
      type: id
      name: footer
      index: 1
  footer_icons:
    enable: true
    left:
      - icon: fa-solid fa-compass
        link: https://youngjuning.js.org/
        desrc: 个人主页
        class: out
      - icon: fa-brands fa-qq
        link: https://res.abeim.cn/api/qq/?qq=2252484287
        desrc: 联系QQ
        class: out
      - icon: fa-brands fa-weixin
        link: https://cdn.jsdelivr.net/gh/youngjuning/images/202109211725265.png
        desrc: 联系微信
        class: in
      - icon: fa-solid fa-envelope
        link: mailto:luozhu2021@gmail.com
        desrc: 发送邮件
        class: out
    right:
      - icon: fa-brands fa-github
        link: https://github.com/youngjuning
        desrc: Github主页
        class: out
      - icon: fab fa-npm
        link: https://www.npmjs.com/~youngjuning
        desrc: NPM
        class: out
      - icon: fa-brands fa-bilibili
        link: https://space.bilibili.com/52457741
        desrc: 哔哩哔哩主页
        class: out
      - icon: fab fa-twitter
        link: https://twitter.com/luozhu2021
        desrc: 推特主页
        class: out
  footer_logo:
    enable: true
    url: https://cdn.jsdelivr.net/gh/youngjuning/images@main/1680450378978.png
  footer_group:
    enable: true
    footer_group_link:
      - group_title: 导航
        footer_links:
          - text: 前端导航
            link: /frontend/
            class: in
          - text: 工具导航
            link: /tool/
            class: in
          - text: 跨境导航
            link: /oversea/
            class: in
          - text: 营销导航
            link: /yingxiao/
            class: in
          - text: 网赚导航
            link: /wangzhuan/
            class: in
          - text: 站长导航
            link: /webmaster/
            class: in
          - text: 科学上网
            link: /vpn/
            class: in
      - group_title: 关于
        footer_links:
          - text: 关于我
            link: /about/
            class: in
          - text: RSS订阅
            link: /atom.xml
            class: in
          - text: 站点监控
            link: https://www.githubstatus.com/
            class: out
          - text: 时间轴
            link: /timeline/
            class: in
          - text: 我的相册
            link: /album/
            class: in
      - group_title: 分类
        footer_links:
          - text: 前端
            link: /categories/前端/
            class: in
          - text: 副业
            link: /categories/副业/
            class: in
          - text: 漫谈
            link: /categories/漫谈/
            class: in
          - text: 加密货币
            link: /categories/加密货币/
            class: in
          - text: 站点运营
            link: /categories/站点运营/
            class: in
          - text: 查看全部
            link: /categories/
            class: in
      - group_title: 时间轴
        footer_links:
          - text: 洛竹
            link: /timeline/luozhu/
            class: in
          - text: ChatGPT
            link: /timeline/chatgpt/
            class: in
          - text: 狗狗币
            link: /timeline/doge/
            class: in
  footer_friend_links:
    enable: false
    number: 5
  footer_bottom:
    copyright:
      enable: true
      author: 洛竹
      link: https://youngjuning.js.org/
      time: 2021
    left:
      - text: Github
        desrc: 本站托管服务
        link: https://github.com/
        icon: fa-brands fa-qq
      - text: jsDelivr
        desrc: 本站 CDN 支持
        link: https://www.jsdelivr.com/
      - text: Gallery
        desrc: 本站图床支持
        link: /gallery/
      - text: JS ORG
        desrc: 本站域名支持
        link: https://js.org/
      - text: RSS2
        desrc: 本站 RSS2 订阅链接
        link: /rss2.xml
      - text: Atom
        desrc: 本站 Atom 格式订阅链接
        link: /atom.xml
    right:
      - text: Hexo
        desrc: 框架
        link: https://hexo.io/zh-cn/
      - text: Butterfly
        desrc: 主题
        link: https://butterfly.js.org/
    runtime:
      enable: true
      time: 2020/01/29 00:00:00
  footer_css: /css/footer.min.css
  footer_js: /js/footer.min.js
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
