name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          npm install -g hexo-cli
          hexo clean
          hexo generate
      # - name: Delete gh-pages branch
      #   run: git push origin --delete gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          cname: yangtp.com