name: CI

on:
  push:
    branches:
      - main

deploy:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use yarn
        uses: c-hive/gha-yarn-cache@v2
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./public
          cname: yangtp.com